#!/bin/sh

#
# run this to download CSV files containing news stories into the current directory.
# control-c it at any time to stop
#
#
# example: Set "MONTHS" to "02" to pull all of Feb.
#

getNews()
{
set -x
cd data/gdelt
TS=`date +"%Y%m%d"`
YEAR="2020"
MONTHS=$1
MONTHS=`date +"%m"`
DAYS=`date -v '-1d' +"%d"`
DAYS=01
DAYS="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31"
HOURS="00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23"
MINS="00 15 30 45"

for i1 in `echo $MONTHS`
do
  for i2 in `echo $DAYS`
  do
    for i3 in `echo $HOURS`
    do
      for i4 in `echo $MINS`
      do
         DAY=${YEAR}${i1}${i2}${i3}${i4}00
        FILE=${DAY}.export
        RET=`ls -1 ${DAY}.export.csv  2>/dev/null|grep -v "No such file or directory"|wc -l`
        if [ $RET -eq 1 ]
        then
          a=a
          #echo "(W) ${FILE} already downloaded"
        else
          rm -f ${FILE}.CSV.zip
          curl -O http://data.gdeltproject.org/gdeltv2/${FILE}.CSV.zip
          RET=$?
          ls -l ${FILE}.CSV.zip
          echo Paused ; read Pause
          if [ "$RET" = "0" ]
          then
            unzip ${FILE}.CSV.zip 1>/dev/null 2>&1
            rm -f ${FILE}.CSV.zip
            mv $FILE.CSV ${FILE}.csv
            docker cp ${FILE}.csv Postgres:/var/tmp
            docker-compose -f ../../docker-compose.yml exec postgres bash -c "psql -U postgres postgres -c \"delete from GDELT_EVENT; \" "
            docker-compose -f ../../docker-compose.yml exec postgres bash -c "psql -U postgres postgres -c \"\\copy GDELT_EVENT FROM '/var/tmp/${FILE}.csv' WITH delimiter E'\t' null as ';' \" "
            docker-compose -f ../../docker-compose.yml exec postgres bash -c "psql -U postgres postgres -c \"SELECT count(*) from GDELT_EVENT;\" "
            rm ${FILE}.csv
          else
             echo "(E) failed to download ${FILE}"
          fi
        fi
       done
     done
   done
done
}
Pause()
{
  echo;echo "Paused"
  read Pause
  clear
  echo;echo
}

getNews
